# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
#

# FROM jupyter/minimal-notebook:177037d09156
# # Get the latest image tag at:
# # https://hub.docker.com/r/jupyter/minimal-notebook/tags/
# # Inspect the Dockerfile at:
# # https://github.com/jupyter/docker-stacks/tree/HEAD/minimal-notebook/Dockerfile

# # install additional package...
# RUN pip install --no-cache-dir astropy    
# RUN pip install nbgitpuller

singleuser:
  image:
    # You should replace the "latest" tag with a fixed version from:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/HEAD/datascience-notebook/Dockerfile
    name: jupyter/datascience-notebook
    tag: ubuntu-20.04

singleuser:
  defaultUrl: "/lab"

singleuser:
  lifecycleHooks:
    postStart:
      exec:
        command:
          [
            "gitpuller",
            "https://github.com/tatsath/tatsath",
            "master",
            "materials-fa",
          ]

hub:
  extraConfig:
    00-first-config: |
      import time
      c.LocalAuthenticator.create_system_users = True
      c.JupyterHub.tornado_settings = {
          "headers": {
              "Content-Security-Policy": "frame-ancestors 'self' *",
              "Access-Control-Allow-Origin": "*",
          }
      }

      c.NotebookApp.tornado_settings = {
          "headers": {
              "Content-Security-Policy": "frame-ancestors 'self' *",
              "Access-Control-Allow-Origin": "*",
          }
      }
      c.NotebookApp.allow_origin = '*'

      
      